### ISSUE TITLE
Springboot-security-oauth2 com Java 10 

### ISSUE THREAD

**Issue by eltonsandre** [algaworks/curso-angular-rest-spring-boot-api#1]
Não estou conseguindo usar o spring boot security com o java 10, springSecurityChainFilter não injeta, e  mesmo usando o web.xml acontece uma exceção devido ao java.xml.bind, alguém já passou por isso?

**Comment by raderleao** [comment]
la no final, atualiza a build adicionando as seguintes linhas no pom:
<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.1.3.RELEASE</version>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>spring-libs-snapshot</id>
			<url>https://repo.spring.io/libs-snapshot</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>spring-plugins-release</id>
			<url>https://repo.spring.io/plugins-release</url>
		</pluginRepository>
		<pluginRepository>
			<id>spring-libs-milestone</id>
			<url>https://repo.spring.io/libs-milestone</url>
		</pluginRepository>
	</pluginRepositories>

**Comment by eltonsandre** [comment]
> la no final, atualiza a build adicionando as seguintes linhas no pom:
> 
> ```
> <build>
>       <plugins>
> 		<plugin>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-maven-plugin</artifactId>
> 			<version>2.1.3.RELEASE</version>
> 		</plugin>
> 	</plugins>
> </build>
> <repositories>
> 	<repository>
> 		<id>spring-libs-snapshot</id>
> 			<url>https://repo.spring.io/libs-snapshot</url>
> 	</repository>
> </repositories>
> <pluginRepositories>
> 	<pluginRepository>
> 		<id>spring-plugins-release</id>
> 		<url>https://repo.spring.io/plugins-release</url>
> 	</pluginRepository>
> 	<pluginRepository>
> 		<id>spring-libs-milestone</id>
> 		<url>https://repo.spring.io/libs-milestone</url>
> 	</pluginRepository>
> </pluginRepositories>
> ```

resolvi um anos atrás rsrs adicionando o modulo no caso do java 10:
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
		</dependency>

**Comment by eltonsandre** [comment]
Resolvi anos atrás adicionando a dependencia abaixo, no caso do modulos do java 10 =>
```
<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
		</dependency>
```
